%% Run forecast scenarios


%% Clear workspace

close all
clear



%% Load models and data

load mat/readModel.mat m
load mat/dates-2021Q4.mat startHist endHist startFcast endFcast
h = databank.fromCSV("csv/initial-conditions-2021Q4.csv");

endExternals = getEnd(h.dl_cpif);
startChart = startFcast - 5*4;


%% Hands-free

f0 = simulate( ...
    m, h, startFcast:endFcast ...
    , "prependInput", true ...
);



%% Add trend and external projections

p1 = Plan.forModel(m, startFcast:endFcast);
p1 = swap( ...
    p1, startFcast:endFcast ...
    , ["dl_y_tnd", "shock_g_y_tnd"] ...
    , ["r_tnd", "shock_r_tnd"] ...
    , ["dl_z_tnd", "shock_dl_z_tnd"] ...
    , ["rf_tnd", "shock_rf_tnd"] ...
);

p1 = swap( ...
    p1, startFcast:endExternals ...
    , ["dl_cpif", "shock_dl_cpif"] ...
    , ["if", "shock_if"] ...
    , ["l_yf_gap", "shock_l_yf_gap"] ...
    ... , ["l_rp_oil_gap", "shock_l_rp_oil_gap"] ...
);


f1 = simulate( ...
    m, h, startFcast:endFcast ...
    , "prependInput", true ...
    , "plan", p1 ...
);


%% Add NTF

p2 = p1;

p2 = swap( ...
    p2, startFcast:startFcast+3 ...
    , ["dl_cpi_core", "shock_dl_cpi_core"] ...
    , ["dl_cpi_ncore", "shock_dl_cpi_ncore"] ...
);

p2 = swap( ...
    p2, startFcast:startFcast+1 ...
    , ["l_y_gap", "shock_l_y_gap"] ...
);

p2 = swap( ...
    p2, startFcast:startFcast ...
    , ["l_s", "shock_l_s"] ...
);


p2 = swap( ...
    p2, startFcast:startFcast ...
    , ["i", "shock_i"] ...
);


f2 = simulate( ...
    m, h, startFcast:endFcast ...
    , "prependInput", true ...
    , "plan", p2 ...
);


%% Add government guarantees for private credit 
%
% Future demand pressures are assumed to be already incorporated in NTF
%

startGuar = qq(2022,3);
endGuar = qq(2023,1);

h3 = f2;
p3 = p2;

p3 = swap(p3, startGuar:endGuar, ["l_y_gap", "shock1_l_y_gap"]);

h3.l_y_gap(startGuar:endGuar) = f2.l_y_gap(startGuar:endGuar) + [1; 1.5; 1.4] * (2/3);

f3 = simulate( ...
    m, h3, startFcast:endFcast ...
    , "prependInput", true ...
    , "plan", p3 ...
);


%% Add government guarantees for private credit 
%
% Future demand pressures are not part of the NTF, allow the variables to
% react on this extra information endogenously
%

startGuar = qq(2022,3);
endGuar = qq(2023,1);

% Run auxiliary simulation

d = steadydb(m, startFcast:endFcast);
d.l_y_gap(startGuar:endGuar) = [1; 1.5; 1.4] * (2/3);
q = Plan.forModel(m, startFcast:endFcast);
q = swap(q, startGuar:endGuar, ["l_y_gap", "shock1_l_y_gap"]);

guar = simulate( ...
    m, d, startFcast:endFcast ...
    , "plan", q ...
);


% Incorporate shocks from auxiliary simulations in forecast

h4 = f2;

h4.shock1_l_y_gap(startGuar:endGuar) = ...
    h4.shock1_l_y_gap(startGuar:endGuar) ...
    + guar.shock_l_y_gap(startGuar:endGuar);

f4 = simulate( ...
    m, h4, startFcast:endFcast ...
    , "prependInput", true ...
);


%% Save baseline to CSV

databank.toCSV( ...
    f3, "csv/baseline-forecast-2021Q4.csv", startHist:endFcast ...
    , "decimals", 16 ...
);






