%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\GDrive\BCT\Matlab_intro\matlab\Day2\data.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 30-Sep-2021 14:22:59

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:V113";

% Specify column names and types
opts.VariableNames = ["VarName1", "GDP", "NOM", "NOM_SA", "INFL", "HUFEUR", "MNB", "BONDR", "DEBTD", "DEBTF", "INTRD", "INTRF", "PBAL", "VAT", "Profit", "Direct_tax", "Contribution", "Sales", "GEXP_SA", "GINC_SA", "RD_SA", "RF_SA"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "VarName1", "InputFormat", "");

% Import the data
tbl = readtable("C:\GDrive\BCT\Matlab_intro\matlab\Day2\data.xlsx", opts, "UseExcel", false);

%% Convert to output type
VarName1 = tbl.VarName1;
GDP = tbl.GDP;
NOM = tbl.NOM;
NOM_SA = tbl.NOM_SA;
INFL = tbl.INFL;
HUFEUR = tbl.HUFEUR;
MNB = tbl.MNB;
BONDR = tbl.BONDR;
DEBTD = tbl.DEBTD;
DEBTF = tbl.DEBTF;
INTRD = tbl.INTRD;
INTRF = tbl.INTRF;
PBAL = tbl.PBAL;
VAT = tbl.VAT;
Profit = tbl.Profit;
Direct_tax = tbl.Direct_tax;
Contribution = tbl.Contribution;
Sales = tbl.Sales;
GEXP_SA = tbl.GEXP_SA;
GINC_SA = tbl.GINC_SA;
RD_SA = tbl.RD_SA;
RF_SA = tbl.RF_SA;

% Rename date vector

quarters = datenum(VarName1);

%% Clear temporary variables
clear opts VarName1